[2022-03-20 11:46:05,129] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2022-03-20T11:45:39.988383+00:00 [queued]>
[2022-03-20 11:46:05,141] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2022-03-20T11:45:39.988383+00:00 [queued]>
[2022-03-20 11:46:05,142] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 11:46:05,142] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 11:46:05,142] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 11:46:05,184] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): processing_user> on 2022-03-20T11:45:39.988383+00:00
[2022-03-20 11:46:05,189] {standard_task_runner.py:52} INFO - Started process 25802 to run task
[2022-03-20 11:46:05,205] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'processing_user', '2022-03-20T11:45:39.988383+00:00', '--job-id', '40', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmphir58lu7', '--error-file', '/tmp/tmp5kglecxu']
[2022-03-20 11:46:05,207] {standard_task_runner.py:77} INFO - Job 40: Subtask processing_user
[2022-03-20 11:46:05,319] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.processing_user 2022-03-20T11:45:39.988383+00:00 [running]> on host airflowvm
[2022-03-20 11:46:05,477] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T11:45:39.988383+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-20T11:45:39.988383+00:00
[2022-03-20 11:46:05,504] {python.py:151} INFO - Done. Returned value was: None
[2022-03-20 11:46:05,510] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20220320T114539, start_date=20220320T114605, end_date=20220320T114605
[2022-03-20 11:46:05,838] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 11:46:05,893] {local_task_job.py:151} INFO - Task exited with return code 0
