[2022-03-20 11:58:51,630] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2020-01-17T00:00:00+00:00 [queued]>
[2022-03-20 11:58:51,645] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2020-01-17T00:00:00+00:00 [queued]>
[2022-03-20 11:58:51,645] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 11:58:51,646] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 11:58:51,646] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 11:58:51,690] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): processing_user> on 2020-01-17T00:00:00+00:00
[2022-03-20 11:58:51,700] {standard_task_runner.py:52} INFO - Started process 33204 to run task
[2022-03-20 11:58:51,741] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'processing_user', '2020-01-17T00:00:00+00:00', '--job-id', '130', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpbvxufig7', '--error-file', '/tmp/tmp9dddojsl']
[2022-03-20 11:58:51,744] {standard_task_runner.py:77} INFO - Job 130: Subtask processing_user
[2022-03-20 11:58:51,996] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.processing_user 2020-01-17T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 11:58:52,130] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2020-01-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-17T00:00:00+00:00
[2022-03-20 11:58:52,156] {python.py:151} INFO - Done. Returned value was: None
[2022-03-20 11:58:52,163] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20200117T000000, start_date=20220320T115851, end_date=20220320T115852
[2022-03-20 11:58:52,270] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 11:58:52,289] {local_task_job.py:151} INFO - Task exited with return code 0
